// Generated by CoffeeScript 1.8.0
var DnDFileController;

DnDFileController = function(selector, onDropCallback) {
  var el_, overCount;
  el_ = document.querySelector(selector);
  overCount = 0;
  this.dragenter = function(e) {
    e.stopPropagation();
    e.preventDefault();
    overCount++;
    show('dragenter');
    el_.classList.add("dropping");
  };
  this.dragover = function(e) {
    e.stopPropagation();
    e.preventDefault();
    show('dragover');
  };
  this.dragleave = function(e) {
    e.stopPropagation();
    e.preventDefault();
    show('dragleave');
    if (--overCount <= 0) {
      el_.classList.remove("dropping");
      overCount = 0;
    }
  };
  this.drop = function(e) {
    e.stopPropagation();
    e.preventDefault();
    show('drop');
    show(e);
    el_.classList.remove("dropping");
    onDropCallback(e.dataTransfer);
  };
  el_.addEventListener("dragenter", this.dragenter, false);
  el_.addEventListener("dragover", this.dragover, false);
  el_.addEventListener("dragleave", this.dragleave, false);
  el_.addEventListener("drop", this.drop, false);
};

module.exports = DnDFileController;
