// Generated by CoffeeScript 1.8.0
var DnDFileController, ProxlyCtrl;

require('angular');

require('angular-sanitize');

require('angular-animate');

ProxlyCtrl = require('../../proxly-ctrl.coffee');

DnDFileController = require('../../dndfile.coffee');

require('../../util.coffee');

chrome.runtime.getBackgroundPage(function(win) {
  var ngRegex, ngapp, nghighlight;
  nghighlight = angular.module("ui.highlight", []).filter("highlight", function() {
    return function(text, search, caseSensitive) {
      if (text && (search || angular.isNumber(search))) {
        text = text.toString();
        search = search.toString();
        if (caseSensitive) {
          return text.split(search).join("<span class=\"ui-match\">" + search + "</span>");
        } else {
          return text.replace(new RegExp(search, "gi"), "<span class=\"ui-match\">$&</span>");
        }
      } else {
        return text;
      }
    };
  });
  ngapp = angular.module('redir', ['ngSanitize', 'ui.highlight', 'ngAnimate']);
  ngapp.factory('proxlyApp', (function(_this) {
    return function() {
      return win.app;
    };
  })(this));
  ngapp.factory('dndFile', function() {
    return DnDFileController;
  });
  ngapp.directive('flipSwitch', function() {
    return {
      restrict: 'AE',
      scope: {
        id: "@identifier",
        toggleThis: '&toggleThis',
        _model: '=ngModel'
      },
      template: '<div class="onoffswitch">\n  <input type="checkbox" name="onoffswitch" id="{{id}}" ng-model="_model" ng-change="toggleThis()" class="onoffswitch-checkbox">\n  <label class="onoffswitch-label" for="{{id}}">\n      <span class="onoffswitch-inner"></span>\n      <span class="onoffswitch-switch"></span>\n  </label>\n</div>',
      replace: true
    };
  });
  ngapp.controller('ProxlyCtrl', ProxlyCtrl);
  ngRegex = ngapp.filter("regex", function() {
    return function(input, field, regex) {
      var i, out, patt;
      patt = new RegExp(regex);
      out = [];
      i = 0;
      if (input == null) {
        return;
      }
      while (i < input.length) {
        if (patt.test(input[i][field])) {
          out.push(input[i]);
        }
        i++;
      }
      return out;
    };
  });
  return angular.bootstrap(document, ['redir']);
});
