// Generated by CoffeeScript 1.7.1
(function() {
  return [].map.call(document.querySelectorAll('script[src],link[href]'), function(e) {
    var url, _ref, _ref1, _ref2;
    url = e.href != null ? e.href : e.src;
    return {
      url: url,
      path: ((_ref = e.attributes['src']) != null ? _ref.value : void 0) != null ? e.attributes['src'].value : (_ref1 = e.attributes['href']) != null ? _ref1.value : void 0,
      href: e.href,
      src: e.src,
      type: e.type,
      tagName: e.tagName,
      extension: (_ref2 = url.match(/\.([^\.]*$)/)) != null ? _ref2[1] : void 0
    };
  }).filter(function(e) {
    if (e.url.match('^(https?)|(chrome-extension)|(file):\/\/.*') != null) {
      return true;
    } else {
      return false;
    }
  });

}).call(this);
