// Generated by CoffeeScript 1.8.0
(function() {
  var resources;

  resources = [].map.call(document.querySelectorAll('script[src],link[href]'), function(e) {
    var url, _ref, _ref1, _ref2;
    url = e.href != null ? e.href : e.src;
    if (url == null) {
      url = '';
    }
    return {
      url: url,
      path: ((_ref = e.attributes['src']) != null ? _ref.value : void 0) != null ? e.attributes['src'].value : (_ref1 = e.attributes['href']) != null ? _ref1.value : void 0,
      href: e.href,
      src: e.src,
      type: e.type,
      tagName: e.tagName,
      extension: (_ref2 = url.match(/\.([^\.]*$)/)) != null ? _ref2[1] : void 0
    };
  }).filter(function(e) {
    var _ref;
    if (((_ref = e.url) != null ? _ref.match('^https?|http?|chrome-extension|file:\/\/.*') : void 0) != null) {
      return true;
    } else {
      return false;
    }
  });

  return resources;

}).call(this);
